apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ssl-kcert
  region: us-east-1

availabilityZones: ["us-east-1a", "us-east-1b"]

managedNodeGroups:
  - name: spot
    instanceType: t3.medium
    desiredCapacity: 2
    spot: true
